
/*--------------------------------------------------------------
| TB_SISTEMA
--------------------------------------------------------------*/
CREATE TABLE TB_SISTEMA (
  COD_SISTEMA INTEGER      NOT NULL,
  NOM_SISTEMA VARCHAR(100) NOT NULL,
  DES_SISTEMA TEXT             NULL,
  IND_ATIVO   INTEGER      NOT NULL DEFAULT '1',
  PRIMARY KEY (COD_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*--------------------------------------------------------------
| TB_CONFIGURACAO
--------------------------------------------------------------*/
CREATE TABLE TB_CONFIGURACAO (
  COD_CONFIGURACAO      INTEGER      NOT NULL AUTO_INCREMENT,
  COD_SISTEMA           INTEGER          NULL,
  NOM_CONFIGURACAO      VARCHAR(100) NOT NULL,
  DES_CONFIGURACAO      VARCHAR(400)     NULL,
  IND_TIPO_CONFIGURACAO VARCHAR(50)  NOT NULL DEFAULT '',
  IND_EXCLUIDO          INTEGER      NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_CONFIGURACAO),
  KEY COD_SISTEMA (COD_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 

ALTER TABLE TB_CONFIGURACAO
  ADD CONSTRAINT FK_CONFIGURACAO_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 

/*--------------------------------------------------------------
| TB_PERFIL
--------------------------------------------------------------*/
CREATE TABLE TB_PERFIL (
  COD_PERFIL       INTEGER      NOT NULL AUTO_INCREMENT, 
  COD_SISTEMA      INTEGER      NOT NULL,
  NOM_PERFIL       VARCHAR(100) NOT NULL,
  DES_CHAVE_PERFIL VARCHAR(200)     NULL,
  IND_ATIVO        INTEGER      NOT NULL DEFAULT '1',
  IND_EXCLUIDO     INTEGER      NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_PERFIL),
  KEY COD_SISTEMA (COD_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE TB_PERFIL
  ADD CONSTRAINT FK_PERFIL_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 

/*--------------------------------------------------------------
| TB_USUARIO
--------------------------------------------------------------*/
CREATE TABLE TB_USUARIO (
  COD_USUARIO                 INTEGER      NOT NULL AUTO_INCREMENT,
  NOM_USUARIO                 VARCHAR(50)  NOT NULL ,
  NOM_LOGIN                   VARCHAR(250) NOT NULL ,
  DES_SENHA                   VARCHAR(100) NOT NULL ,
  NUM_CPF                     VARCHAR(11)      NULL ,
  NUM_TELEFONE                VARCHAR(20)      NULL,
  NUM_CELULAR                 VARCHAR(20)      NULL,
  DES_EMAIL                   VARCHAR(150)     NULL,
  DES_FOTO                    BLOB             NULL,
  DAT_CADASTRO                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COD_RESPONSAVEL_CADASTRO    INTEGER          NULL,
  DAT_ATUALIZACAO             TIMESTAMP        NULL,
  COD_RESPONSAVEL_ATUALIZACAO INTEGER          NULL,
  IND_ATIVO                   INTEGER      NOT NULL DEFAULT '1',
  IND_EXCLUIDO                INTEGER      NOT NULL DEFAULT '0',
  
  PRIMARY KEY (COD_USUARIO),
  KEY COD_RESPONSAVEL_CADASTRO (COD_RESPONSAVEL_CADASTRO),
  KEY COD_RESPONSAVEL_ATUALIZACAO (COD_RESPONSAVEL_ATUALIZACAO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE TB_USUARIO
  ADD CONSTRAINT FK_USUARIO_CADASTRO
    FOREIGN KEY (COD_RESPONSAVEL_CADASTRO)
      REFERENCES TB_USUARIO (COD_USUARIO);
      
ALTER TABLE TB_USUARIO
  ADD CONSTRAINT FK_USUARIO_ATUALIZACAO
    FOREIGN KEY (COD_RESPONSAVEL_ATUALIZACAO)
      REFERENCES TB_USUARIO (COD_USUARIO); 
      

/*--------------------------------------------------------------
| RL_USUARIO_PERFIL
--------------------------------------------------------------*/
CREATE TABLE RL_USUARIO_PERFIL (
  COD_USUARIO                 INTEGER   NOT NULL, 
  COD_PERFIL                  INTEGER   NOT NULL,
  DAT_CADASTRO                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COD_RESPONSAVEL_CADASTRO    INTEGER       NULL,
  DAT_ATUALIZACAO             TIMESTAMP     NULL,
  COD_RESPONSAVEL_ATUALIZACAO INTEGER       NULL,
  IND_ATIVO                   INTEGER   NOT NULL DEFAULT '1',
  IND_EXCLUIDO                INTEGER   NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_USUARIO, COD_PERFIL),
  KEY COD_RESPONSAVEL_CADASTRO (COD_RESPONSAVEL_CADASTRO),
  KEY COD_RESPONSAVEL_ATUALIZACAO (COD_RESPONSAVEL_ATUALIZACAO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE RL_USUARIO_PERFIL
  ADD CONSTRAINT FK_USUARIO_PERFIL_USUARIO
    FOREIGN KEY (COD_USUARIO)
      REFERENCES TB_USUARIO (COD_USUARIO);

ALTER TABLE RL_USUARIO_PERFIL
  ADD CONSTRAINT FK_USUARIO_PERFIL_PERFIL
    FOREIGN KEY (COD_PERFIL)
      REFERENCES TB_PERFIL (COD_PERFIL);

ALTER TABLE RL_USUARIO_PERFIL
  ADD CONSTRAINT FK_USUARIO_PERFIL_CADASTRO
    FOREIGN KEY (COD_RESPONSAVEL_CADASTRO)
      REFERENCES TB_USUARIO (COD_USUARIO);
      
ALTER TABLE RL_USUARIO_PERFIL
  ADD CONSTRAINT FK_USUARIO_PERFIL_ATUALIZACAO
    FOREIGN KEY (COD_RESPONSAVEL_ATUALIZACAO)
      REFERENCES TB_USUARIO (COD_USUARIO);
/*--------------------------------------------------------------
| TB_MENU
--------------------------------------------------------------*/
CREATE TABLE TB_MENU (
  COD_MENU       INTEGER      NOT NULL AUTO_INCREMENT,
  COD_MENU_PAI   INTEGER          NULL,
  COD_SISTEMA    INTEGER      NOT NULL,
  DES_CHAVE_MENU VARCHAR(200)     NULL,
  NOM_MENU       VARCHAR(50)  NOT NULL,
  URL_PAGINA     VARCHAR(1000)    NULL,
  DES_ICONE      VARCHAR(1000)    NULL, 
  NUM_ORDEM_MENU INTEGER      NOT NULL DEFAULT '1',
  IND_VISIVEL    INTEGER      NOT NULL DEFAULT '1',
  IND_EXCLUIDO   INTEGER      NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_MENU),
  KEY COD_MENU_PAI (COD_MENU_PAI),
  KEY COD_SISTEMA (COD_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE TB_MENU
  ADD CONSTRAINT FK_MENU_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 
      
ALTER TABLE TB_MENU
  ADD CONSTRAINT FK_MENU_PAI
    FOREIGN KEY (COD_MENU_PAI)
      REFERENCES TB_MENU (COD_MENU); 
/*--------------------------------------------------------------
| RL_PERFIL_MENU
--------------------------------------------------------------*/
CREATE TABLE RL_PERFIL_MENU (
  COD_PERFIL INTEGER NOT NULL, 
  COD_MENU   INTEGER NOT NULL, 
  PRIMARY KEY (COD_PERFIL, COD_MENU)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE RL_PERFIL_MENU
  ADD CONSTRAINT FK_PERFIL_MENU_MENU
    FOREIGN KEY (COD_MENU)
      REFERENCES TB_MENU (COD_MENU);

ALTER TABLE RL_PERFIL_MENU
  ADD CONSTRAINT FK_PERFIL_MENU_PERFIL
    FOREIGN KEY (COD_PERFIL)
      REFERENCES TB_PERFIL (COD_PERFIL);
/*--------------------------------------------------------------
| TB_APLICACAO_CLIENTE
--------------------------------------------------------------*/
CREATE TABLE TB_APLICACAO_CLIENTE (
  COD_APLICACAO_CLIENTE   VARCHAR(256) NOT NULL,
  COD_SISTEMA             INTEGER          NULL,
  DES_CLIENT_SECRET       VARCHAR(256)     NULL,
  DES_GRANT_TYPE          VARCHAR(50)      NULL,
  DAT_CADASTRO            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NUM_REFRESH_TOKEN       INTEGER      NOT NULL DEFAULT '15',
  IND_VALIDA_ORIGEM_TOKEN INTEGER      NOT NULL DEFAULT '1',
  IND_ATIVO               INTEGER      NOT NULL DEFAULT '1',
  IND_EXCLUIDO            INTEGER      NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_APLICACAO_CLIENTE),
  KEY COD_SISTEMA (COD_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE TB_APLICACAO_CLIENTE
  ADD CONSTRAINT FK_APLICACAO_CLIENTE_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 
/*--------------------------------------------------------------
| TB_ACCES_TOKEN
--------------------------------------------------------------*/
CREATE TABLE TB_ACCES_TOKEN (
  DES_ACCES_TOKEN         VARCHAR(256) NOT NULL ,
  COD_APLICACAO_CLIENTE   VARCHAR(256) NOT NULL ,
  COD_SISTEMA             INTEGER      NOT NULL,
  COD_USUARIO             INTEGER          NULL, 
  NUM_TEMPO_VALIDADE      INTEGER      NOT NULL DEFAULT '15',
  DES_REFRESH_TOKEN       VARCHAR(256)     NULL  ,
  DES_TIPO_TOKEN          VARCHAR(10)      NULL,
  DES_USER_AGENT          VARCHAR(250)     NULL,
  DES_BROWSER             VARCHAR(250)     NULL ,
  DES_VERSAO_BROWSER      VARCHAR(250)     NULL ,
  DES_SISTEMA_OPERACIONAL VARCHAR(250)     NULL,
  DES_IP                  VARCHAR(100)     NULL ,
  DAT_CADASTRO            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DAT_ATUALIZACAO         TIMESTAMP        NULL,
  IND_VALIDO              INTEGER      NOT NULL DEFAULT '1',
  PRIMARY KEY (DES_ACCES_TOKEN),
  KEY COD_SISTEMA (COD_SISTEMA),
  KEY COD_APLICACAO_CLIENTE (COD_APLICACAO_CLIENTE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

 
ALTER TABLE TB_ACCES_TOKEN
  ADD CONSTRAINT TB_ACCES_TOKEN_APLICACAO
    FOREIGN KEY (COD_APLICACAO_CLIENTE)
      REFERENCES TB_APLICACAO_CLIENTE (COD_APLICACAO_CLIENTE); 
      
ALTER TABLE TB_ACCES_TOKEN
  ADD CONSTRAINT TB_ACCES_TOKEN_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 
/*--------------------------------------------------------------
| TB_RECURSO
--------------------------------------------------------------*/
CREATE TABLE TB_RECURSO (
  COD_RECURSO       INTEGER      NOT NULL AUTO_INCREMENT,
  COD_SISTEMA       INTEGER      NOT NULL,
  NOM_RECURSO       VARCHAR(250)     NULL ,
  URL_RECURSO       VARCHAR(500)     NULL, 
  DES_CHAVE_RECURSO VARCHAR(200)     NULL,
  DAT_CADASTRO      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  IND_ATIVO         INTEGER      NOT NULL DEFAULT '1',
  IND_EXCLUIDO      INTEGER      NOT NULL DEFAULT '0',
  PRIMARY KEY (COD_RECURSO),
  KEY COD_SISTEMA (COD_SISTEMA) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 

ALTER TABLE TB_RECURSO
  ADD CONSTRAINT TB_RECURSO_SISTEMA
    FOREIGN KEY (COD_SISTEMA)
      REFERENCES TB_SISTEMA (COD_SISTEMA); 
/*--------------------------------------------------------------
| RL_APLICACAO_RECURSO
--------------------------------------------------------------*/
CREATE TABLE RL_APLICACAO_RECURSO (
  COD_APLICACAO_CLIENTE   VARCHAR(256) NOT NULL , 
  COD_RECURSO INTEGER     NOT NULL, 
  NOM_METODO  VARCHAR(10) NOT NULL  ,
  PRIMARY KEY (COD_APLICACAO_CLIENTE, COD_RECURSO, NOM_METODO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE RL_APLICACAO_RECURSO
  ADD CONSTRAINT RL_APLICACAO_RECURSO_RECURSO
    FOREIGN KEY (COD_RECURSO)
      REFERENCES TB_RECURSO (COD_RECURSO);

ALTER TABLE RL_APLICACAO_RECURSO
  ADD CONSTRAINT RL_APLICACAO_RECURSO_APLICACAO_CLIENTE
    FOREIGN KEY (COD_APLICACAO_CLIENTE)
      REFERENCES TB_APLICACAO_CLIENTE (COD_APLICACAO_CLIENTE); 
       
/*--------------------------------------------------------------
| RL_PERFIL_RECURSO
--------------------------------------------------------------*/
CREATE TABLE RL_PERFIL_RECURSO (
  COD_PERFIL  INTEGER     NOT NULL, 
  COD_RECURSO INTEGER     NOT NULL, 
  NOM_METODO  VARCHAR(10) NOT NULL  ,
  PRIMARY KEY (COD_PERFIL, COD_RECURSO, NOM_METODO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE RL_PERFIL_RECURSO
  ADD CONSTRAINT RL_PERFIL_RECURSO_RECURSO
    FOREIGN KEY (COD_RECURSO)
      REFERENCES TB_RECURSO (COD_RECURSO);

ALTER TABLE RL_PERFIL_RECURSO
  ADD CONSTRAINT RL_PERFIL_RECURSO_PERFIL
    FOREIGN KEY (COD_PERFIL)
      REFERENCES TB_PERFIL (COD_PERFIL); 

/*--------------------------------------------------------------
| VW_PERMISSAO_RECURSO
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_PERMISSAO_RECURSO AS
SELECT CONCAT(COD_RECURSO, '.', NOM_METODO) AS COD_PERMISSAO
     , COD_RECURSO
     , NOM_METODO
FROM RL_PERFIL_RECURSO
;
/*--------------------------------------------------------------
| VW_PERMISSAO_RECURSO_PERFIL
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_PERMISSAO_RECURSO_PERFIL AS
SELECT DISTINCT 
       CONCAT(COD_RECURSO, '.', NOM_METODO, '.', COD_PERFIL) AS ID 
     , CONCAT(COD_RECURSO, '.', NOM_METODO) AS COD_PERMISSAO 
     , COD_PERFIL 
FROM RL_PERFIL_RECURSO
;
/*--------------------------------------------------------------
| VW_MENU_USUARIO_SISTEMA
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_MENU_USUARIO_SISTEMA AS
SELECT MENU.COD_MENU
     , MENU.COD_MENU_PAI
     , MENU.COD_SISTEMA
     , MENU.IND_VISIVEL
     , MENU.NOM_MENU
     , MENU.NUM_ORDEM_MENU
     , MENU.URL_PAGINA
     , MENU.DES_ICONE
     , USUARIO_PERFIL.COD_USUARIO

FROM TB_MENU MENU 

	INNER JOIN RL_PERFIL_MENU PERFIL_MENU ON PERFIL_MENU.COD_MENU = MENU.COD_MENU
	
	INNER JOIN TB_PERFIL PERFIL ON PERFIL.COD_PERFIL = PERFIL_MENU.COD_PERFIL
	
	INNER JOIN RL_USUARIO_PERFIL USUARIO_PERFIL 
		ON  USUARIO_PERFIL.COD_PERFIL   = PERFIL.COD_PERFIL 
		AND USUARIO_PERFIL.IND_EXCLUIDO = 0
;
/*--------------------------------------------------------------
| VW_USUARIO_SISTEMA
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_USUARIO_SISTEMA AS
SELECT USUARIO.COD_USUARIO
      ,USUARIO.NOM_USUARIO
      ,USUARIO.NOM_LOGIN
      ,USUARIO.DES_EMAIL
      ,USUARIO.NUM_CPF
      ,USUARIO.NUM_TELEFONE
      ,USUARIO.NUM_CELULAR
      ,USUARIO_PERFIL.IND_ATIVO
      ,USUARIO.IND_EXCLUIDO
      ,USUARIO.DAT_CADASTRO
      ,USUARIO.COD_RESPONSAVEL_CADASTRO
      ,USUARIO.DAT_ATUALIZACAO
      ,USUARIO.COD_RESPONSAVEL_ATUALIZACAO
      
      ,PERFIL.COD_PERFIL
      ,PERFIL.NOM_PERFIL
      ,PERFIL.DES_CHAVE_PERFIL
      
      ,SISTEMA.COD_SISTEMA
      ,SISTEMA.NOM_SISTEMA
      
FROM TB_USUARIO USUARIO

	LEFT JOIN RL_USUARIO_PERFIL USUARIO_PERFIL 
	ON  USUARIO_PERFIL.COD_USUARIO = USUARIO.COD_USUARIO
	AND USUARIO_PERFIL.IND_EXCLUIDO = 0 
	
	LEFT JOIN TB_PERFIL PERFIL ON PERFIL.COD_PERFIL = USUARIO_PERFIL.COD_PERFIL
	
	LEFT JOIN TB_SISTEMA SISTEMA ON SISTEMA.COD_SISTEMA = PERFIL.COD_SISTEMA
	
WHERE USUARIO.IND_EXCLUIDO = 0
; 
/*--------------------------------------------------------------
| VW_USUARIO_RESPONSAVEL
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_USUARIO_RESPONSAVEL AS
SELECT COD_USUARIO
      ,NOM_USUARIO
      ,NOM_LOGIN
      ,DES_EMAIL 
      ,IND_ATIVO
      ,IND_EXCLUIDO
FROM TB_USUARIO  
;

/*--------------------------------------------------------------
| VW_ACCES_TOKEN_AUTENTICADO
--------------------------------------------------------------*/
CREATE OR REPLACE VIEW VW_ACCES_TOKEN_AUTENTICADO AS
SELECT TOKEN.DES_ACCES_TOKEN
      ,TOKEN.DES_TIPO_TOKEN
      ,RECURSO.COD_RECURSO
      ,RECURSO.URL_RECURSO
      ,RL_RECURSO.NOM_METODO
      ,TOKEN.DES_IP
      ,USUARIO.COD_USUARIO
      ,USUARIO.NOM_USUARIO
      ,USUARIO.NOM_LOGIN
      ,PERFIL.COD_PERFIL
      ,PERFIL.NOM_PERFIL
      ,TOKEN.COD_SISTEMA
      ,APLICACAO_CLIENTE.IND_VALIDA_ORIGEM_TOKEN
      ,TOKEN.IND_VALIDO
FROM TB_ACCES_TOKEN TOKEN

	INNER JOIN TB_APLICACAO_CLIENTE APLICACAO_CLIENTE ON APLICACAO_CLIENTE.COD_APLICACAO_CLIENTE = TOKEN.COD_APLICACAO_CLIENTE 
	INNER JOIN TB_USUARIO USUARIO ON USUARIO.COD_USUARIO = TOKEN.COD_USUARIO 
	INNER JOIN RL_USUARIO_PERFIL RL_PERFIL ON RL_PERFIL.COD_USUARIO = USUARIO.COD_USUARIO
	INNER JOIN TB_PERFIL PERFIL ON PERFIL.COD_PERFIL = RL_PERFIL.COD_PERFIL AND PERFIL.COD_SISTEMA = TOKEN.COD_SISTEMA
	INNER JOIN RL_PERFIL_RECURSO RL_RECURSO ON RL_RECURSO.COD_PERFIL = PERFIL.COD_PERFIL 
	INNER JOIN TB_RECURSO RECURSO ON RECURSO.COD_RECURSO = RL_RECURSO.COD_RECURSO 
	
WHERE RECURSO.IND_EXCLUIDO = 0 

UNION

SELECT TOKEN.DES_ACCES_TOKEN
      ,TOKEN.DES_TIPO_TOKEN
      ,RECURSO.COD_RECURSO
      ,RECURSO.URL_RECURSO
      ,RL.NOM_METODO
      ,TOKEN.DES_IP
      ,NULL
      ,NULL
      ,NULL
      ,NULL
      ,NULL
      ,TOKEN.COD_SISTEMA
      ,APLICACAO_CLIENTE.IND_VALIDA_ORIGEM_TOKEN
      ,TOKEN.IND_VALIDO
FROM TB_ACCES_TOKEN TOKEN

	INNER JOIN TB_APLICACAO_CLIENTE APLICACAO_CLIENTE ON APLICACAO_CLIENTE.COD_APLICACAO_CLIENTE = TOKEN.COD_APLICACAO_CLIENTE  
	INNER JOIN RL_APLICACAO_RECURSO RL ON RL.COD_APLICACAO_CLIENTE = TOKEN.COD_APLICACAO_CLIENTE 
	INNER JOIN TB_RECURSO RECURSO ON RECURSO.COD_RECURSO = RL.COD_RECURSO 
	
WHERE RECURSO.IND_EXCLUIDO = 0 

;       
       
       
        


      
      
      
      
      
      
      
























