--------------------------------------------------------
--  File created - Friday-July-20-2018   
--------------------------------------------------------
-- Unable to render TABLE DDL for object BD_BASI.RL_APLICACAO_RECURSO_SISTEMA with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_APLICACAO_RECURSO_SISTEMA ON BD_BASI.RL_APLICACAO_RECURSO_SISTEMA (ID_APLICACAO_CLIENTE ASC, CD_RECURSO_SISTEMA ASC, NM_METODO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.RL_APLICACAO_RECURSO_SISTEMA 
(
  ID_APLICACAO_CLIENTE VARCHAR2(256 BYTE) NOT NULL 
, CD_RECURSO_SISTEMA NUMBER(10, 0) NOT NULL 
, NM_METODO VARCHAR2(7 BYTE) NOT NULL 
, CONSTRAINT PK_APLICACAO_RECURSO_SISTEMA PRIMARY KEY 
  (
    ID_APLICACAO_CLIENTE 
  , CD_RECURSO_SISTEMA 
  , NM_METODO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.RL_APLICACAO_RECURSO_SISTEMA
ADD CONSTRAINT FK_APLIC_REC_SISTEMA_APLICACAO FOREIGN KEY
(
  ID_APLICACAO_CLIENTE 
)
REFERENCES BD_BASI.TB_APLICACAO_CLIENTE
(
  ID_APLICACAO_CLIENTE 
)
ENABLE
ALTER TABLE BD_BASI.RL_APLICACAO_RECURSO_SISTEMA
ADD CONSTRAINT FK_APLIC_REC_SISTEMA_RECURSO FOREIGN KEY
(
  CD_RECURSO_SISTEMA 
)
REFERENCES BD_BASI.TB_RECURSO_SISTEMA
(
  CD_RECURSO_SISTEMA 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.RL_PERFIL_ACESSO_MENU with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_PERFIL_ACESSO_MENU ON BD_BASI.RL_PERFIL_ACESSO_MENU (CD_PERFIL_ACESSO ASC, CD_MENU ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.RL_PERFIL_ACESSO_MENU 
(
  CD_PERFIL_ACESSO NUMBER(10, 0) NOT NULL 
, CD_MENU NUMBER(10, 0) NOT NULL 
, CONSTRAINT PK_PERFIL_ACESSO_MENU PRIMARY KEY 
  (
    CD_PERFIL_ACESSO 
  , CD_MENU 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.RL_PERFIL_ACESSO_MENU
ADD CONSTRAINT FK_PERFIL_ACESSO_MENU_MENU FOREIGN KEY
(
  CD_MENU 
)
REFERENCES BD_BASI.TB_MENU
(
  CD_MENU 
)
ENABLE
ALTER TABLE BD_BASI.RL_PERFIL_ACESSO_MENU
ADD CONSTRAINT FK_PERFIL_ACESSO_MENU_PERFIL FOREIGN KEY
(
  CD_PERFIL_ACESSO 
)
REFERENCES BD_BASI.TB_PERFIL_ACESSO
(
  CD_PERFIL_ACESSO 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.RL_PERFIL_RECURSO_SISTEMA with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_PERFIL_RECURSO_SISTEMA ON BD_BASI.RL_PERFIL_RECURSO_SISTEMA (CD_PERFIL_ACESSO ASC, CD_RECURSO_SISTEMA ASC, NM_METODO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.RL_PERFIL_RECURSO_SISTEMA 
(
  CD_PERFIL_ACESSO NUMBER(10, 0) NOT NULL 
, CD_RECURSO_SISTEMA NUMBER(10, 0) NOT NULL 
, NM_METODO VARCHAR2(7 BYTE) NOT NULL 
, CONSTRAINT PK_PERFIL_RECURSO_SISTEMA PRIMARY KEY 
  (
    CD_PERFIL_ACESSO 
  , CD_RECURSO_SISTEMA 
  , NM_METODO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.RL_PERFIL_RECURSO_SISTEMA
ADD CONSTRAINT FK_PERFIL_REC_SISTEMA_PERFIL FOREIGN KEY
(
  CD_PERFIL_ACESSO 
)
REFERENCES BD_BASI.TB_PERFIL_ACESSO
(
  CD_PERFIL_ACESSO 
)
ENABLE
ALTER TABLE BD_BASI.RL_PERFIL_RECURSO_SISTEMA
ADD CONSTRAINT FK_PERFIL_REC_SISTEMA_RECURSO FOREIGN KEY
(
  CD_RECURSO_SISTEMA 
)
REFERENCES BD_BASI.TB_RECURSO_SISTEMA
(
  CD_RECURSO_SISTEMA 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.RL_USUARIO_PERFIL_ACESSO with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_USUARIO_PERFIL_ACESSO ON BD_BASI.RL_USUARIO_PERFIL_ACESSO (CD_USUARIO ASC, CD_PERFIL_ACESSO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.RL_USUARIO_PERFIL_ACESSO 
(
  CD_USUARIO NUMBER(10, 0) NOT NULL 
, CD_PERFIL_ACESSO NUMBER(10, 0) NOT NULL 
, DT_CADASTRO TIMESTAMP(6) 
, CD_RESPONSAVEL_CADASTRO NUMBER(10, 0) 
, DT_ATUALIZACAO TIMESTAMP(6) 
, CD_RESPONSAVEL_ATUALIZACAO NUMBER(10, 0) 
, FL_EXCLUIDO CHAR(1 BYTE) DEFAULT '0' 
, FL_ATIVO CHAR(1 BYTE) DEFAULT 1 NOT NULL 
, FL_RECEBE_EMAIL CHAR(1 BYTE) DEFAULT 1 
, FL_ASSINANTE CHAR(1 BYTE) DEFAULT 1 
, CONSTRAINT PK_USUARIO_PERFIL_ACESSO PRIMARY KEY 
  (
    CD_USUARIO 
  , CD_PERFIL_ACESSO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.RL_USUARIO_PERFIL_ACESSO
ADD CONSTRAINT FK_USUARIO_PERFIL_ACES_PERFIL FOREIGN KEY
(
  CD_PERFIL_ACESSO 
)
REFERENCES BD_BASI.TB_PERFIL_ACESSO
(
  CD_PERFIL_ACESSO 
)
ENABLE
ALTER TABLE BD_BASI.RL_USUARIO_PERFIL_ACESSO
ADD CONSTRAINT FK_USUARIO_PERFIL_ACES_USUARIO FOREIGN KEY
(
  CD_USUARIO 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.RL_USUARIO_SISTEMA_PESSOA with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_RL_USUARIO_SISTEMA_PESSOA ON BD_BASI.RL_USUARIO_SISTEMA_PESSOA (CD_USUARIO ASC, CD_SISTEMA ASC, CD_PESSOA ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.RL_USUARIO_SISTEMA_PESSOA 
(
  CD_USUARIO NUMBER(10, 0) NOT NULL 
, CD_SISTEMA NUMBER(10, 0) NOT NULL 
, CD_PESSOA NUMBER(10, 0) NOT NULL 
, DT_CADASTRO TIMESTAMP(6) 
, CD_RESPONSAVEL_CADASTRO NUMBER(10, 0) 
, DT_ATUALIZACAO TIMESTAMP(6) 
, CD_RESPONSAVEL_ATUALIZACAO NUMBER(10, 0) 
, FL_EXCLUIDO CHAR(1 BYTE) DEFAULT '0' 
, CONSTRAINT PK_RL_USUARIO_SISTEMA_PESSOA PRIMARY KEY 
  (
    CD_USUARIO 
  , CD_SISTEMA 
  , CD_PESSOA 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.RL_USUARIO_SISTEMA_PESSOA
ADD CONSTRAINT FK_USUARIO_SIST_PESSOA_SISTEMA FOREIGN KEY
(
  CD_SISTEMA 
)
REFERENCES BD_BASI.TB_SISTEMA
(
  CD_SISTEMA 
)
ENABLE
ALTER TABLE BD_BASI.RL_USUARIO_SISTEMA_PESSOA
ADD CONSTRAINT FK_USUARIO_SIST_PESSOA_USUARIO FOREIGN KEY
(
  CD_USUARIO 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_ACCES_TOKEN with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_ACCES_TOKEN ON BD_BASI.TB_ACCES_TOKEN (DS_ACCES_TOKEN ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_ACCES_TOKEN 
(
  DS_ACCES_TOKEN VARCHAR2(256 BYTE) DEFAULT NULL NOT NULL 
, DS_TIPO_TOKEN VARCHAR2(10 BYTE) DEFAULT NULL 
, NR_TEMPO_VALIDADE NUMBER(10, 0) 
, DS_SCOPE VARCHAR2(50 BYTE) DEFAULT NULL 
, ID_APLICACAO_CLIENTE VARCHAR2(256 BYTE) DEFAULT NULL 
, DS_REFRESH_TOKEN VARCHAR2(256 BYTE) DEFAULT NULL 
, DS_ID_USER_AGENT VARCHAR2(250 BYTE) 
, NR_IP VARCHAR2(100 BYTE) 
, CD_USUARIO NUMBER(10, 0) 
, DT_CADASTRO TIMESTAMP(6) DEFAULT SYSDATE 
, DT_ATUALIZACAO TIMESTAMP(6) 
, FL_VALIDO CHAR(1 BYTE) DEFAULT '1' 
, CD_SISTEMA NUMBER(10, 0) 
, DS_BROWSER VARCHAR2(250 BYTE) 
, DS_VERSAO_BROWSER VARCHAR2(250 BYTE) 
, DS_SISTEMA_OPERACIONAL VARCHAR2(250 BYTE) 
, CONSTRAINT PK_ACCES_TOKEN PRIMARY KEY 
  (
    DS_ACCES_TOKEN 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- Unable to render TABLE DDL for object BD_BASI.TB_APLICACAO_CLIENTE with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_APLICACAO_CLIENTE ON BD_BASI.TB_APLICACAO_CLIENTE (ID_APLICACAO_CLIENTE ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_APLICACAO_CLIENTE 
(
  ID_APLICACAO_CLIENTE VARCHAR2(256 BYTE) NOT NULL 
, FL_SECRET_REQUIRED CHAR(1 BYTE) DEFAULT '1' 
, DS_CLIENT_SECRET VARCHAR2(256 BYTE) DEFAULT NULL 
, NM_APLICACAO_CLIENTE VARCHAR2(256 BYTE) 
, FL_SCOPE CHAR(1 BYTE) DEFAULT '1' 
, DS_SCOPE VARCHAR2(256 BYTE) DEFAULT NULL 
, DS_GRANT_TYPE VARCHAR2(50 BYTE) NOT NULL 
, DS_WEB_SERVER_REDIRECT_URI VARCHAR2(256 BYTE) DEFAULT NULL 
, DT_CADASTRO DATE DEFAULT NULL 
, CD_SISTEMA NUMBER(10, 0) 
, FL_PERMITE_ATUALIZACAO_TOKEN CHAR(1 BYTE) DEFAULT '0' 
, FL_CARREGA_MENU_SISTEMA CHAR(1 BYTE) DEFAULT '1' 
, FL_CARREGA_PERFIL_SISTEMA CHAR(1 BYTE) DEFAULT '1' 
, FL_CARREGA_NOTIFICACAO_SISTEMA CHAR(1 BYTE) DEFAULT '1' 
, FL_CARREGA_EMAIL_SISTEMA CHAR(1 BYTE) DEFAULT '1' 
, FL_ACESSO_USUARIO_EXTERNO CHAR(1 BYTE) DEFAULT '1' 
, QT_MINUTOS_VALIDADE_TOKEN NUMBER(5, 0) DEFAULT 15 
, FL_VALIDA_ORIGEM_TOKEN CHAR(1 BYTE) DEFAULT '1' 
, FL_VALIDA_USUARIO_SISTEMA CHAR(1 BYTE) DEFAULT '1' 
, DS_URL_TROCA_SENHA VARCHAR2(150 BYTE) 
, FL_PRINCIPAL CHAR(1 BYTE) DEFAULT '1' NOT NULL 
, CONSTRAINT PK_APLICACAO_CLIENTE PRIMARY KEY 
  (
    ID_APLICACAO_CLIENTE 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- Unable to render TABLE DDL for object BD_BASI.TB_CONFIGURACAO with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_CONFIGURACAO ON BD_BASI.TB_CONFIGURACAO (CD_CONFIGURACAO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_CONFIGURACAO 
(
  CD_CONFIGURACAO NUMBER(10, 0) NOT NULL 
, NM_PROPRIEDADE VARCHAR2(100 BYTE) NOT NULL 
, VL_PROPRIEDADE VARCHAR2(4000 BYTE) NOT NULL 
, CD_TIPO_CONFIGURACAO NUMBER(10, 0) NOT NULL 
, CD_SISTEMA NUMBER(10, 0) 
, FL_CONTROLE_EXCLUSAO CHAR(1 BYTE) 
, CONSTRAINT PK_CONFIGURACAO PRIMARY KEY 
  (
    CD_CONFIGURACAO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.TB_CONFIGURACAO
ADD CONSTRAINT FK_CONFIGURACAO_SISTEMA FOREIGN KEY
(
  CD_SISTEMA 
)
REFERENCES BD_BASI.TB_SISTEMA
(
  CD_SISTEMA 
)
ENABLE
ALTER TABLE BD_BASI.TB_CONFIGURACAO
ADD CONSTRAINT FK_CONFIGURACAO_TIPO_CONFIG FOREIGN KEY
(
  CD_TIPO_CONFIGURACAO 
)
REFERENCES BD_BASI.TB_TIPO_CONFIGURACAO
(
  CD_TIPO_CONFIGURACAO 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_MENU with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_MENU ON BD_BASI.TB_MENU (CD_MENU ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_MENU 
(
  CD_MENU NUMBER(10, 0) NOT NULL 
, NM_MENU VARCHAR2(250 BYTE) NOT NULL 
, DS_MENU VARCHAR2(4000 BYTE) 
, NR_ITEM_MENU NUMBER(2, 0) 
, NR_ORDEM_MENU NUMBER(2, 0) 
, DS_URL_PAGINA VARCHAR2(200 BYTE) 
, NM_ICO_MENU VARCHAR2(200 BYTE) 
, DS_STYLE_MENU VARCHAR2(200 BYTE) 
, FL_VISIVEL CHAR(1 BYTE) DEFAULT '1' NOT NULL 
, CD_MENU_SUPERIOR NUMBER(10, 0) 
, DS_IDENTIFICACAO_MENU VARCHAR2(200 BYTE) 
, CD_SISTEMA NUMBER(10, 0) 
, FL_CONTROLE_EXCLUSAO CHAR(1 BYTE) 
, CONSTRAINT PK_MENU PRIMARY KEY 
  (
    CD_MENU 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.TB_MENU
ADD CONSTRAINT FK_MENU_MENU_SUPERIOR FOREIGN KEY
(
  CD_MENU_SUPERIOR 
)
REFERENCES BD_BASI.TB_MENU
(
  CD_MENU 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_PERFIL_ACESSO with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_PERFIL_ACESSO ON BD_BASI.TB_PERFIL_ACESSO (CD_PERFIL_ACESSO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_PERFIL_ACESSO 
(
  CD_PERFIL_ACESSO NUMBER(5, 0) NOT NULL 
, NM_PERFIL_ACESSO VARCHAR2(60 BYTE) NOT NULL 
, DS_PERFIL_ACESSO VARCHAR2(4000 BYTE) 
, FL_TIPO_PERFIL CHAR(2 BYTE) 
, CD_SISTEMA NUMBER(5, 0) NOT NULL 
, NM_PAGINA_PRINCIPAL VARCHAR2(250 BYTE) 
, DS_IDENTIFICACAO_PERFIL VARCHAR2(200 BYTE) 
, FL_CONTROLE_EXCLUSAO CHAR(1 BYTE) 
, CONSTRAINT PK_PERFIL_ACESSO PRIMARY KEY 
  (
    CD_PERFIL_ACESSO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.TB_PERFIL_ACESSO
ADD CONSTRAINT FK_PERFIL_ACESSO_SISTEMA FOREIGN KEY
(
  CD_SISTEMA 
)
REFERENCES BD_BASI.TB_SISTEMA
(
  CD_SISTEMA 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_RECURSO_SISTEMA with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_RECURSO_SISTEMA ON BD_BASI.TB_RECURSO_SISTEMA (CD_RECURSO_SISTEMA ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_RECURSO_SISTEMA 
(
  CD_RECURSO_SISTEMA NUMBER(10, 0) NOT NULL 
, NM_RECURSO_SISTEMA VARCHAR2(250 BYTE) NOT NULL 
, DS_RECURSO_SISTEMA VARCHAR2(120 BYTE) 
, DS_URL_RECURSO_SISTEMA VARCHAR2(200 BYTE) NOT NULL 
, FL_ATIVO CHAR(1 BYTE) DEFAULT '1' NOT NULL 
, CD_SISTEMA NUMBER(5, 0) NOT NULL 
, DS_IDENTIFICACAO_RECURSO VARCHAR2(200 BYTE) 
, FL_CONTROLE_EXCLUSAO CHAR(1 BYTE) 
, CONSTRAINT PK_RECURSO_SISTEMA PRIMARY KEY 
  (
    CD_RECURSO_SISTEMA 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE BD_BASI.TB_RECURSO_SISTEMA
ADD CONSTRAINT FK_RECURSO_SISTEMA_SISTEMA FOREIGN KEY
(
  CD_SISTEMA 
)
REFERENCES BD_BASI.TB_SISTEMA
(
  CD_SISTEMA 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_SISTEMA with DBMS_METADATA attempting internal generator.
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_SISTEMA IS 'Número sequencial que identifica o registro do sistema.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_SISTEMA IS 'Nome por extenso do sistema.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_SISTEMA IS 'Descrição sobre o sistema, explicar suscintamente o que é, o que faz';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_SITUACAO_ATUAL IS 'Descrição da situacao atual em que se encontra o sistemaa';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DT_IMPLANTACAO IS 'Data da implantação do sistema.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_ANALISTA_NEGOCIO IS 'Código que identifica o Analista de Negócio reponsável pelo sistema na ATI, que vem da tabela TB_PESSOA';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_GESTOR_SISTEMA IS 'Código que identifica o Gestor do Sistema na área de negócio, que vem da tabela TB_PESSOA';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_PROJETO IS 'Código do projeto do sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_TIPO_CRITICIDADE IS 'Identificação do tipo da criticadade do sistema (média, baixa, alta, etc)';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_URL_PRODUCAO IS 'Nome da url (endereço) do sistema no ambiente de produção';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_URL_HOMOLOGACAO IS 'Nome da url (endereço) do sistema no ambiente de homologação';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_URL_DESENVOLVIMENTO IS 'Nome da url (endereço) do sistema no ambiente de desenvolvimento';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_TIPO_CONEXAO_BD IS 'Descrição do tipo de conexão com o banco de dados, como datasource, cliente;servidor, odbc';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DT_DESATIVACAO IS 'Data de desativação do sistema, caso ele tenha sido desativado';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_AVALIACAO_PLANO_ACAO IS 'Descrição da avaliação do plano de ação, se o sistema é para ser mantido, para avaliar, para desativar., etc';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.VL_PERCENTUAL_CRITICIDADE IS 'Valor do percentual de criticadade do sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DT_EXCLUSAO_FISICA IS 'Data da exclusão física do banco de dados';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_DETALHAM_CONTRATO IS 'Descrição do detalhamento do contrato deste sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_OBJETIVO_ESTRATEGICO IS 'Descrição do objetivo estratégico deste sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_MODALIDADE IS 'Modalidade de aquisição do sistema, se D - Desenvolvimento ou C - Compra';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_NUM_VERSAO_ATUAL IS 'Descrição do número da versão atual deste sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_USO_DR IS 'Iidentifica se o DR usa este sistema ou não (S ou N)';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_DETALHAM_INFORMACAO IS 'Descrição do detalhamento de informações sobre este sistema';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_URL_SVN IS 'Nome da url do sistema no SVN';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_URL_SEGURANCAXML IS 'Nome a url da segurança do sistema em xml';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_FORNECEDOR IS 'Código que identifica o fornecedor que desenvolveu o sistema (sempre o fornecedor mais atual), que vem do PROTHEUS< portanto não possui FK.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NM_BANCO_DADOS IS 'Nome do banco de dados do sistema. Exemplo: sistema OBA, tem o nome do banco OBA';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_ATIVO IS 'Indica se este sistema está Ativo - A ou Inativo - I';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.SG_SISTEMA IS 'Sigla do Sistema.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_FASE_ATUAL IS 'Descrição da fase em que o sistema se encontra atualmente, como desenvolvimento, parado, em análise, em produção, cancelado, etc.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_TIPO_HOSPEDAGEM IS 'Indica o tipo de hospedagem E - Externa , I - Interna';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.NR_PONTOS_FUNCAO IS 'Identifica a quantidade de pontos de função do sistema.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_AREA_RESPONSAVEL IS 'Còdigo que identifica a área responsável pelo Sistema. Esta coluna será usada no sistema de informações de dados, a ser especificado até dezembro de 2017.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DT_ATUALIZACAO IS 'Data/hora da última atualização do registro.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_RESPONSAVEL_ATUALIZACAO IS 'Código do usuário (correspondente na tabela TB_USUARIO) responsável pela última atualização do registro.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_EXCLUIDO IS 'Indica se o registro está lógicamente excluído.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_LOG_ALTERACAO IS 'Registra o histórico de alterações realizadas no registro';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DT_CADASTRO IS 'Data/hora da criação do registro.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_RESPONSAVEL_CADASTRO IS 'Código do usuário (correspondente na tabela TB_USUARIO) responsável pela criação do registro.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.CD_TIPO_SOLUCAO_TECNOLOGICA IS 'Código sequencial de identificação única do tipo da solução tecnológica a que o sistema em questão pertence.';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_VERSAO_DESENVOLVIMENTO IS 'Informação sogre a Versão do sistema em Desenvolvimento';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_VERSAO_HOMOLOGACAO IS 'Informação sogre a Versão do sistema em Homologação';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.DS_VERSAO_PRODUCAO IS 'Informação sogre a Versão do sistema em Produção';
COMMENT ON COLUMN BD_BASI.TB_SISTEMA.FL_PERMITE_ATUALIZACAO IS 'Indica se o sistema permite atualização S - Sim ou N - Não.';CREATE UNIQUE INDEX BD_BASI.PK_SISTEMA ON BD_BASI.TB_SISTEMA (CD_SISTEMA ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCOMMENT ON TABLE BD_BASI.TB_SISTEMA IS 'Armazena as informações sobre os sistemas da CNI.'CREATE TABLE BD_BASI.TB_SISTEMA 
(
  CD_SISTEMA NUMBER(5, 0) NOT NULL 
, NM_SISTEMA VARCHAR2(100 BYTE) NOT NULL 
, DS_SISTEMA VARCHAR2(4000 BYTE) 
, DS_SITUACAO_ATUAL VARCHAR2(20 BYTE) DEFAULT 'ANALISE' NOT NULL 
, DT_IMPLANTACAO DATE 
, CD_ANALISTA_NEGOCIO NUMBER(10, 0) 
, CD_GESTOR_SISTEMA NUMBER(10, 0) 
, CD_PROJETO NUMBER(5, 0) 
, CD_TIPO_CRITICIDADE NUMBER(10, 0) 
, NM_URL_PRODUCAO VARCHAR2(350 BYTE) 
, NM_URL_HOMOLOGACAO VARCHAR2(350 BYTE) 
, NM_URL_DESENVOLVIMENTO VARCHAR2(350 BYTE) 
, DS_TIPO_CONEXAO_BD VARCHAR2(150 BYTE) 
, DT_DESATIVACAO DATE 
, DS_AVALIACAO_PLANO_ACAO VARCHAR2(100 BYTE) 
, VL_PERCENTUAL_CRITICIDADE VARCHAR2(150 BYTE) 
, DT_EXCLUSAO_FISICA DATE 
, DS_DETALHAM_CONTRATO VARCHAR2(4000 BYTE) 
, DS_OBJETIVO_ESTRATEGICO VARCHAR2(4000 BYTE) 
, FL_MODALIDADE CHAR(1 BYTE) 
, DS_NUM_VERSAO_ATUAL VARCHAR2(100 BYTE) 
, FL_USO_DR CHAR(1 BYTE) 
, DS_DETALHAM_INFORMACAO VARCHAR2(4000 BYTE) 
, NM_URL_SVN VARCHAR2(350 BYTE) 
, NM_URL_SEGURANCAXML VARCHAR2(350 BYTE) 
, CD_FORNECEDOR VARCHAR2(150 BYTE) 
, NM_BANCO_DADOS VARCHAR2(150 BYTE) 
, FL_ATIVO CHAR(1 BYTE) 
, SG_SISTEMA VARCHAR2(50 BYTE) 
, DS_FASE_ATUAL VARCHAR2(150 BYTE) 
, FL_TIPO_HOSPEDAGEM CHAR(1 BYTE) 
, NR_PONTOS_FUNCAO NUMBER(10, 0) 
, CD_AREA_RESPONSAVEL NUMBER(10, 0) 
, DT_ATUALIZACAO TIMESTAMP(6) 
, CD_RESPONSAVEL_ATUALIZACAO NUMBER(10, 0) 
, FL_EXCLUIDO CHAR(1 BYTE) DEFAULT 'N' NOT NULL 
, DS_LOG_ALTERACAO CLOB 
, DT_CADASTRO TIMESTAMP(6) 
, CD_RESPONSAVEL_CADASTRO NUMBER(10, 0) 
, CD_TIPO_SOLUCAO_TECNOLOGICA NUMBER(10, 0) 
, CD_TIPO_CATEGORIA_SISTEMA NUMBER(10, 0) 
, DS_VERSAO_DESENVOLVIMENTO VARCHAR2(100 BYTE) 
, DS_VERSAO_HOMOLOGACAO VARCHAR2(100 BYTE) 
, DS_VERSAO_PRODUCAO VARCHAR2(100 BYTE) 
, FL_PERMITE_ATUALIZACAO CHAR(1 BYTE) 
, CONSTRAINT PK_SISTEMA PRIMARY KEY 
  (
    CD_SISTEMA 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (DS_LOG_ALTERACAO) STORE AS SYS_LOB0000557750C00037$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
)ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_ATIVO_SISTEMA CHECK 
(FL_ATIVO IS NULL OR FL_ATIVO IN ('A', 'I'))
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_EXCLUIDO_SISTEMA CHECK 
(FL_EXCLUIDO IN ('S','N'))
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_MODALIDADE_SISTEMA CHECK 
(FL_MODALIDADE IS NULL OR (FL_MODALIDADE IN ('D','C')))
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_PERMITE_ATUALIZ_SISTEMA CHECK 
(FL_PERMITE_ATUALIZACAO IS NULL OR (FL_PERMITE_ATUALIZACAO IN ('S','N')))
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_TIPO_HOSPEDAGEM_SISTEMA CHECK 
(FL_TIPO_HOSPEDAGEM IS NULL OR (FL_TIPO_HOSPEDAGEM IN ('E','I')))
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT CKC_FL_USO_DR CHECK 
(FL_USO_DR IS NULL OR (FL_USO_DR IN ('S','N')))
ENABLEALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT FK_SISTEMA_USR_ANALISTA_NEG FOREIGN KEY
(
  CD_ANALISTA_NEGOCIO 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT FK_SISTEMA_USR_GESTOR_SISTEMA FOREIGN KEY
(
  CD_GESTOR_SISTEMA 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT FK_SISTEMA_USR_RESPON_ATUALIZA FOREIGN KEY
(
  CD_RESPONSAVEL_ATUALIZACAO 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
ALTER TABLE BD_BASI.TB_SISTEMA
ADD CONSTRAINT FK_SISTEMA_USR_RESPON_CADASTRO FOREIGN KEY
(
  CD_RESPONSAVEL_CADASTRO 
)
REFERENCES BD_BASI.TB_USUARIO
(
  CD_USUARIO 
)
ENABLE
-- Unable to render TABLE DDL for object BD_BASI.TB_USUARIO with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX BD_BASI.PK_USUARIO ON BD_BASI.TB_USUARIO (CD_USUARIO ASC) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE BD_BASI.TB_USUARIO 
(
  CD_USUARIO NUMBER(10, 0) NOT NULL 
, NM_USUARIO VARCHAR2(60 BYTE) NOT NULL 
, NM_LOGIN VARCHAR2(150 BYTE) NOT NULL 
, DS_EMAIL VARCHAR2(150 BYTE) 
, NR_CPF VARCHAR2(11 BYTE) 
, NR_CNPJ VARCHAR2(14 BYTE) 
, NR_DDD_TELEFONE VARCHAR2(3 BYTE) 
, NR_TELEFONE VARCHAR2(11 BYTE) 
, NR_DDD_CELULAR VARCHAR2(3 BYTE) 
, NR_CELULAR VARCHAR2(11 BYTE) 
, FL_INTERNO NUMBER(1, 0) NOT NULL 
, DT_ULTIMO_LOGON DATE 
, NR_TENTATIVAS_LOGON NUMBER(3, 0) DEFAULT 0 NOT NULL 
, FL_BLOQUEADO NUMBER(1, 0) DEFAULT 0 NOT NULL 
, DS_SENHA_TEMP VARCHAR2(128 BYTE) 
, DT_SENHA_TEMP DATE 
, FL_TROCA_SENHA NUMBER(1, 0) DEFAULT 0 NOT NULL 
, FL_ATIVO NUMBER(1, 0) DEFAULT 1 NOT NULL 
, DT_CADASTRO TIMESTAMP(6) NOT NULL 
, CD_RESPONSAVEL_CADASTRO NUMBER(10, 0) NOT NULL 
, DT_ATUALIZACAO TIMESTAMP(6) 
, CD_RESPONSAVEL_ATUALIZACAO NUMBER(10, 0) 
, FL_EXCLUIDO CHAR(1 BYTE) DEFAULT 'N' NOT NULL 
, DS_CARGO VARCHAR2(200 BYTE) 
, FOTO CLOB 
, CONSTRAINT PK_USUARIO PRIMARY KEY 
  (
    CD_USUARIO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE BD_BASI_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (FOTO) STORE AS SYS_LOB0000510829C00025$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING  
)
